apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: andfaxle/authentication:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3300
          volumeMounts:
            - name: auth-data
              mountPath: /mount
          env:
            - name: DB_PATH
              value: "/mount/auth.db"
      volumes:
        - name: auth-data
          persistentVolumeClaim:
            claimName: auth-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300
      nodePort: 30081
  type: NodePort

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auth-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: auth-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/auth"
