apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-deployment
  labels:
    app: shortener
spec:
  selector:
    matchLabels:
      app: shortener
  replicas: 1
  template:
    metadata:
      labels:
        app: shortener
    spec:
      containers:
        - name: shortener
          image: andfaxle/url-shortener:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_SERVICE_URL
              value: "http://145.100.135.226:30081"
          ports:
            - containerPort: 3200

---
apiVersion: v1
kind: Service
metadata:
  name: shortener-service
spec:
  selector:
    app: shortener
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
      nodePort: 30082
  type: NodePort
